version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: tasky_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tasky_db
      POSTGRES_USER: tasky_user
      POSTGRES_PASSWORD: tasky_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
